#!/usr/bin/env bash
#
# A dynamic scala runner, using coursier's app launch capabilities.
# Author: Dale Wijnand <dale.wijnand@gmail.com>
# https://github.com/dwijnand/scala-runners

shopt -s extglob # for extended pattern matching operators, like `+([0-9])`

app_name=$(basename "$0")

declare app_name
declare scala_version=latest.stable
declare scala3
declare -a java_args residual_args
declare verbose print_scala_version

declare -r scala_ea_builds_url=https://scala-ci.typesafe.com/artifactory/scala-integration
declare -r scala_pr_builds_url=https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots

echoerr() { echo >&2 "$@"; }
vlog()    { [[ -n "$verbose" ]] && echoerr "$@"; }
die()     { echo "Aborting: $*"; exit 1; }
dropR()   { echo "${1:0:$((${#1} - $2))}"; } # https://superuser.com/q/1033273 ${1:0:-5} (bash 4.2+)

checkCurl() { command -v curl &> /dev/null || die "curl command required"; }
checkCs()   { command -v cs   &> /dev/null || die "cs command required";   }
checkJq()   { command -v jq   &> /dev/null || die "jq command required";   }
checkHub()  {
  command -v hub &> /dev/null || die "hub command required"
  if [ ! -f "${HOME}/.config/hub" ]; then
    echo "No hub config found (at ~/.config/hub).  Triggering hub to prompt you for credentials."
    hub api
  fi
}

addJava()     { vlog "[addJava] arg = '$1'";         java_args+=("--java-opt" "$1"); }
addCoursier() { vlog "[addCoursier] arg = '$1'"; coursier_args+=("$1");              }

getScalaBaseVersion() {
  vlog "[getScalaBaseVersion] arg = '$1'"
  local build_sbt
  build_sbt=$(hub api -H "Accept: application/vnd.github.v3.raw" "repos/scala/scala/contents/build.sbt?ref=$1")
  [ $? -ne 0 ] && exit 1
  local base_version=$(grep -E '(baseVersion in Global|Global / baseVersion\b)' <<< "$build_sbt" | sed 's/.*"\(.*\)".*/\1/')
  local cross=$(grep -q -E '\d+\.\d+.0' <<< "$base_version" && echo "-pre" || echo "-bin")
  echo "$base_version$cross"
}

getScalaHead() {
  vlog "[getScalaHead] arg = '$1'"
  local base_version
  base_version=$(getScalaBaseVersion "heads/$1")
  [ $? -ne 0 ] && exit 1
  local refInfo=$(hub api "repos/scala/scala/git/ref/heads/$1")
  local sha=$(jq -r '.object.sha' <<< "$refInfo")
  echo "$base_version-${sha:0:7}"
}

getScalaNext() {
  vlog "[getScalaNext] arg = '$1'"
  curl -Ls "https://raw.github.com/scala/community-build/$1/nightly.properties" \
    | sed -n 's/nightly=\(.*\)/\1/p'
}

setCoursierOptionsForSv() {
  case "$scala_version" in
    *-@(bin|pre)-*SNAPSHOT) addCoursier "-r=$scala_pr_builds_url" ;;
    *-@(bin|pre)-*)         addCoursier "-r=$scala_ea_builds_url" ;;
    *+)                     addCoursier "--no-default" && addCoursier "-r=central" ;;
  esac
  case "$scala_version" in
    *-SNAPSHOT) addCoursier "--ttl=24h" ;;
    *+)         addCoursier "--ttl=24h" ;;
  esac
}

setOptionsForSv() {
  setCoursierOptionsForSv
  if [[ -n "$scala3" ]]; then
    case "$app_name" in
        scalac) app_name="scala3-compiler"   ;;
         scala) app_name="scala3-repl"       ;;
      scaladoc) app_name="scala3-doc"        ;;
        scalap) app_name="scala3-decompiler" ;;
    esac
  fi
}

setScalaVersion() {
  vlog "[setScalaVersion] arg = '$1'"
  case "$1" in
    *.head) checkJq && checkHub; scala_version=$(getScalaHead "$(dropR "$1" 5).x") ;;
    *.next) checkCurl; scala_version=$(getScalaNext "$(dropR "$1" 5).x") ;;
         *)           scala_version="$1"
  esac
  [ $? -ne 0 ] && die "Failed to set scala version given arg $1"
  case "$scala_version" in
    3*) scala3=true ;;
  esac
  setOptionsForSv
}

setScalaPrVersion() {
  vlog "[setScalaPrVersion] arg = '$1'"
  local base_version
  checkJq && checkHub
  base_version=$(getScalaBaseVersion "pull/$1/head")
  [ $? -ne 0 ] && die "Failed to get scala base version for PR $1"
  local prInfo=$(hub api "repos/scala/scala/pulls/$1")
  local sha=$(jq -r '.head.sha' <<< "$prInfo")
  setScalaVersion "$base_version-${sha:0:7}-SNAPSHOT"
}

usage() {
  cat <<EOM
Usage: \$script_name [options]

Where, "script_name" is scala, scalac, scaladoc, or scalap.

All options not specified below are passed through.

  -h | -help         print this message (only when script_name is scala-runner)
  -v                 verbose operation (this runner is chattier)

  # scala version (default: latest.stable, resolved by Couriser)
  -28                        use the latest 2.8.x release
  -29                        use the latest 2.9.x release
  -210                       use the latest 2.10.x release
  -211                       use the latest 2.11.x release
  -212                       use the latest 2.12.x release
  -213                       use the latest 2.13.x release
  -2.12.next                 use the next candidate 2.12.x release (from the community build)
  -2.13.next                 use the next candidate 2.13.x release
  -2.12.head                 use the latest build from the HEAD of the 2.12.x branch (latest "merge-ly")
  -2.13.head                 use the latest build from the HEAD of the 2.13.x branch
  -3                         use the latest 3.x release
  -3.head                    use the latest 3.x nightly release
  -<version>                 use the specified scala version, e.g. -2.13.6 or -3.0.1
  --scala-version <version>  use the specified scala version, e.g. --scala-version 3.1-my-test
  --scala-pr <PR number>     use the version of scala built from the specified PR

  # passing options to the jvm
  -Dkey=val         pass -Dkey=val directly to the jvm
  -J-X              pass option -X directly to the jvm

  # passing options to coursier
  -C-X              pass option -X directly to coursier (-C is stripped)

  --print-scala-version      prints the resolved scala version
EOM
  exit 0
}

require_arg() {
  local type="$1"
  local opt="$2"
  local arg="$3"

  if [[ -z "$arg" ]] || [[ "${arg:0:1}" == "-" ]]; then
    echo "Aborting: $opt requires <$type> argument"
    exit 1
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
                      -h | -help) [[ "$app_name" == "scala-runner" ]] && usage || residual_args+=("$1") && shift ;;
                              -v) verbose=true && shift ;;
                             -28) setScalaVersion "2.8+"   && shift ;;
                             -29) setScalaVersion "2.9+"   && shift ;;
                            -210) setScalaVersion "2.10+"  && shift ;;
                            -211) setScalaVersion "2.11+"  && shift ;;
                            -212) setScalaVersion "2.12+"  && shift ;;
                            -213) setScalaVersion "2.13+"  && shift ;;
          -2.1[2-4].@(head|next)) setScalaVersion "${1:1}" && shift ;; # 2.1[2-4].head or 2.1[2-4].next
     -2.@([89]|1[0-4]).+([0-9])*) setScalaVersion "${1:1}" && shift ;; # 2.[89].z* or 2.1[0-4].z*
                              -3) scala3=true && setOptionsForSv && shift ;;
                         -3.head) setScalaVersion "3+"     && shift ;;
                       # -3.next)  && shift ;;
                             -3*) setScalaVersion "${1:1}" && shift ;;
                 --scala-version) require_arg version     "$1" "$2" && setScalaVersion   "$2" && shift 2 ;;
                      --scala-pr) require_arg "PR number" "$1" "$2" && setScalaPrVersion "$2" && shift 2 ;;
                             -C*) addCoursier "${1:2}"     && shift ;;
                             -D*) addJava "$1"             && shift ;;
                             -J*) addJava "${1:2}"         && shift ;;
           --print-scala-version) print_scala_version=1    && shift ;;
                               *) residual_args+=("$1")    && shift ;;
  esac
done

execRunner() {
  # print the arguments one to a line, quoting any containing spaces
  vlog "# Executing command line:" && {
    for arg; do
      if [[ -n "$arg" ]]; then
        if printf "%s\n" "$arg" | grep -q ' '; then
          printf >&2 "\"%s\"\n" "$arg"
        else
          printf >&2 "%s\n" "$arg"
        fi
      fi
    done
    vlog ""
  }

  "$@"
}

checkCs

if [[ -n "$print_scala_version" ]]; then
  case "$scala_version" in
    *.*.*)
      sv="$scala_version" ;;
    *)
      checkJq
      json_file="$(mktemp -t scala-runner.cs-fetch.XXXXXX.json)"
      execRunner cs fetch  -j "$json_file" "$app_name:$scala_version" "${coursier_args[@]}" >/dev/null 2>&1
      sv=$(jq -r <"$json_file" '[.[]] | .[0] | [.[]] | .[0]' | cut -d: -f3)
      ;;
  esac
  echo "$sv"
  exit
fi

execRunner cs launch \
  "$app_name:$scala_version" \
  "${java_args[@]}" \
  "${coursier_args[@]}" \
  -- "${residual_args[@]}"
